.TH "macat" 1 "February 11, 2015" "mangos " "mangos"
.SH NAME
macat \- command line interface to the mangos messaging library
.SH SYNOPSIS
macat  [\-v|\-\-verbose] [\-q|\-\-silent] [\-\-push] [\-\-pull] [\-\-pub] [\-\-sub] [\-\-req] [\-\-rep] [\-\-surveyor] [\-\-respondent] [\-\-bus] [\-\-pair] [\-\-star] [\-\-bind ADDR] [\-\-connect ADDR] [\-X|\-\-bind-ipc PATH] [\-x|\-\-connect-ipc PATH] [\-L|\-\-bind-local PORT] [\-l|\-\-connect-local PORT] [\-\-subscribe PREFIX] [\-\-recv-timeout SEC] [\-\-send-timeout SEC] [\-d|\-\-send-delay SEC] [\-\-raw] [\-A|\-\-ascii] [\-Q|\-\-quoted] [\-\-msgpack] [\-i|\-\-interval SEC] [\-D|\-\-data DATA] [\-F|\-\-file FILE] [\-E|\-\-cert FILE] [\-\-key FILE] [\-\-cacert FILE] [\-k|\-\-insecure] [\-\-help]
.SH DESCRIPTION
The macat command is a command-line interface to
send and receive
data via the mangos implementation of the SP (nanomsg) protocols.  It is
designed to be suitable for use as a drop-in replacement for nanocat(1).

.SH OPTIONS
.TP
\-v,\-\-verbose
Increase verbosity
.TP
\-q,\-\-silent
Decrease verbosity
.TP
\-\-push
Use PUSH socket type
.TP
\-\-pull
Use PULL socket type
.TP
\-\-pub
Use PUB socket type
.TP
\-\-sub
Use SUB socket type
.TP
\-\-req
Use REQ socket type
.TP
\-\-rep
Use REP socket type
.TP
\-\-surveyor
Use SURVEYOR socket type
.TP
\-\-respondent
Use RESPONDENT socket type
.TP
\-\-bus
Use BUS socket type
.TP
\-\-pair
Use PAIR socket type
.TP
\-\-star
Use STAR socket type
.TP
\-\-bind ADDR
Bind socket to ADDR
.TP
\-\-connect ADDR
Connect socket to ADDR
.TP
\-X,\-\-bind-ipc PATH
Bind socket to IPC PATH
.TP
\-x,\-\-connect-ipc PATH
Connect socket to IPC PATH
.TP
\-L,\-\-bind-local PORT
Bind socket to TCP localhost PORT
.TP
\-l,\-\-connect-local PORT
Connect socket to TCP localhost PORT
.TP
\-\-subscribe PREFIX
Subcribe to PREFIX (default is wildcard)
.TP
\-\-recv-timeout SEC
Set receive timeout
.TP
\-\-send-timeout SEC
Set send timeout
.TP
\-d,\-\-send-delay SEC
Set initial send delay
.TP
\-\-raw
Raw output, no delimiters
.TP
\-A,\-\-ascii
ASCII output, one per line
.TP
\-Q,\-\-quoted
Quoted output, one per line
.TP
\-\-msgpack
Msgpacked binay output (see msgpack.org)
.TP
\-i,\-\-interval SEC
Send DATA every SEC seconds
.TP
\-D,\-\-data DATA
Data to send
.TP
\-F,\-\-file FILE
Send contents of FILE
.TP
\-E,\-\-cert FILE
Use certificate in FILE for SSL/TLS
.TP
\-\-key FILE
Use private key in FILE for SSL/TLS
.TP
\-\-cacert FILE
Use CA certicate(s) in FILE for SSL/TLS
.TP
\-k,\-\-insecure
Do not validate TLS/SSL peer certificate
.TP
\-\-help
show usage message
.SH AUTHOR
Garrett D'Amore
